### ISSUE TITLE
Properties Hotkey not functioning in V2.4

### ISSUE THREAD

**Issue by shan2752** [MrZammler/iGame#213]
Amiga P hotkey doesn’t seem to be working in new version.  Thanks!

**Comment by walkero-gr** [comment]
Thank you for your report. I can assure you that it is working fine. I wonder if there is a conflict with something on your system. I would like to know more details of your setup. What OS are you running?

**Comment by shan2752** [comment]
Hi, thanks for all of your work!  When I upgraded to V2.4.0, the hotkey no longer seems to work.  I am running Workbench 3.1.4 on a PAL A1200 with ACA 1233n 40mhz.  I press Amiga and P keys and there is no response.

**Comment by walkero-gr** [comment]
@shan2752 I think I managed to reproduce it. This happens only if you are using MUI 3.8, which I guess you do. I will find the issue and will include it in the next release.
Thank you for letting me know about it.

**Comment by walkero-gr** [comment]
@shan2752  As I said I managed to reproduce it but it seems to be a bug in NList with MUI 3.8. Sometimes NList captures the keyboard shortcuts. This doesn't allow any iGame menu shortcut to be used. 

Sometimes if you click outside the list while you have it selected the menu shortcuts work just fine.

I found that if you disable the "Keyboard moves cursor" in NListviews prefs it helps the situation and the events seem to work much better
Here is a screenshot of where to find it.
![Screenshot from 2023-05-21 22-40-33](https://github.com/MrZammler/iGame/assets/14014909/65749679-ff30-4f5a-bd12-14f984a755f9)

This issue doesn't seem to exist with MUI 5.0.

Please give it a try on the above and let me know if it works better this way for you. Otherwise, I am afraid you have to use the menu items.

**Comment by shan2752** [comment]
Yes, I am using MUI 3.8.  Not a large issue for me, especially since mirv2k provided his igame.dat.  I will post a larger issue under a new comment.  Thanks!
