### ISSUE TITLE
Make iGame work with lha archives?

### ISSUE THREAD

**Issue by Fredrikzett** [MrZammler/iGame#217]
Would it be possible to make iGame identify lha archives also?
Starting the game would extract it to ram: (or another place), then run it from there and after quiting it would clean up the folder...

I made an amigados script that does this but it has no front end with pictures...

**Comment by walkero-gr** [comment]
@Fredrikzett I am sorry but it is out of scope of iGame. I don't see how this is useful to anyone and why iGame do something like that. Would you like to explain the benefits of such a feature?

**Comment by Fredrikzett** [comment]
@walkero-gr  Well, it takes less place on your harddrive and it's convenient as all games/demos already comes as lha. For instance, there is a download tool that updates your library and it does so by installing lha archives...

**Comment by walkero-gr** [comment]
@Fredrikzett I am not negative about such a feature but allow me to have my doubts about how useful this is. 

Sure, a game takes less space on disk, but I see the following problems that will need to be addressed:
- When a game is selected, as you also described, this will need to be extracted in memory. This is a slow process and will take time since a user starts a game and the starts itself
- The games will not be able to have screenshots unless they are stored somewhere else which will require the user to have a specific structure of them. Usually, things like that are difficult to happen right from the user side, no matter how many guidelines are given. It is harder than "_Put the image in the game folder with name iGame.iff_". 
This will also require a big refactoring on the iGame code to make this happen, a path should be added in preferences so that the user can point to where the screenshots are stored.
- The same with screenshots will happen for the newly introduced iGame.data.
- The user will need to have extra memory available which might increase the hardware requirements
- There will be no way for iGame to recognise if a game is WHDLoad-based or anything else, not before extracting it. This means that during the scan process, it won't be possible to get the name and type (whdload or something else).
- All the above to make it happen need good code refactoring while the current way of working should be retained without issues. Which means that the code will become bigger and more complicated to maintain.

All these and many more technical issues make that request not so beneficial in my eyes, and I am sorry about it.
I understand that you want to save space but I hope I described properly to you why this is not the solution to that problem. Maybe a bigger SD card could be a better solution. I hope you understand.

**Comment by walkero-gr** [comment]
duplicate #42

**Comment by Fredrikzett** [comment]
I understand, no problems :)
