### ISSUE TITLE
On game launch WHDLoad freezes on splash screen

### ISSUE THREAD

**Issue by gsanjin** [MrZammler/iGame#218]
When starting game from list, WHDLoad starts (splash screen appears) and just freezes. Nothing appears on RGB output, RTG screen freezes with WHDLoad splash screen and frozen mouse. OS 3.2, 3.2.2, 3.2.2.1, MUI components ok, MUI 3.8. Starting same WHDLoad slaves from workbench, shell, dopu4 works without issue. Tested on versions 2.3, 2.3.2 and 2.4.0. using 040 compile bin.

**Comment by walkero-gr** [comment]
@gsanjin Thank you so much for your message. 
If the WHDLoad starts just fine, then up to that point iGame's work is done. 

Have you tried an older version though and see if that exists there as well? I would suggest trying version 2.2.1 https://github.com/MrZammler/iGame/releases/tag/v2.2.1 

If that version works fine then it will mean that I possibly broke something since V2.3.0 and above. These versions had a lot of changes. If it still has the same problems then I guess it is something on your system.
I would suggest you do an installation to different folders, so as to have both versions. And please do not mess the gamelists between the versions, because they are not compatible with each other.

Please let me know how it goes.

**Comment by gsanjin** [comment]
Thanks for replay and sorry for long delay in response!

I just tested with 2.2.1 and 2.1 (each with clean repos scan)- and same problem ...

WHDLoad splash screen starts just fine but disappears immediately and then freezes. Mouse doesn't disappear on RTG screen like when whdload starts from WB/shell. It behaves like s:whdload.prefs is not even taken in consideration (there is defined splash screen delay for couple of secs). I am using 040 version on Emu68 AOS 3.2.2.1 ...

**Comment by walkero-gr** [comment]
Do you use any specific tooltypes in the games' icons for your system? What I assume is happening is that some kind of tooltype is ignored which is necessary for the games and the rtg switch to work fine. Can you share with me your s:whdload.prefs ?

**Comment by gsanjin** [comment]
All is ok, issue can be closed. It was my fault.
I had some command in s:whdload-startup which was executing ok but with notification (so return error code, d0 register, was not 0) but with output to nil: and I was missing it whole time.

**Comment by walkero-gr** [comment]
@gsanjin I am really glad you found the issue. Have fun with iGame and thank you for letting us know.
