### ISSUE TITLE
Get Game titles from Directories instead of only Slave contents

### ISSUE THREAD

**Issue by midwan** [MrZammler/iGame#5]
Unfortunately, many times the Slave contents do not contain the correct game title. This results in duplicate titles, that are automatically appended with "Alt". If there are several duplicates, those get extra "Alt" in their title, ending up with situations like this:

"Alt Alt Alt Alt Alt Alt game title"

If you have a large game collection, the number of these duplicates can be quite big, and the number of "Alt" prefixes can grow so long that it doesn't even fit the window horizontally.

I propose that we add an alternative way of detecting the game title: By the name of the directory the slave is located into.

It's much easier for users to keep an organized and properly named directory structure for their games, but it's very difficult to change the titles contained in the .slave files.

This could be an option (either use Directories or Slaves for the titles) that is saved in the program preferences.

**Comment by wepl** [comment]
Alternative the name of Icon could be used for naming.
The current approach by scanning the slaves fits anyway no my kind of installation where I may have multiple icons/data-dirs and only one slave for multiple language versions of a game.
Selectable scanner would be useful.

**Comment by midwan** [comment]
Thanks @wepl that's an interesting point indeed.

**Comment by midwan** [comment]
Example screenshots of old version VS new version:

![img_2709](https://user-images.githubusercontent.com/3877365/43995356-9e8bf7ae-9dac-11e8-8cc3-b2d5d1dee7c8.JPG)

![img_2710](https://user-images.githubusercontent.com/3877365/43995357-9ea9c932-9dac-11e8-90a2-18a353ff2803.JPG)


Notice the directory names I had, had no spaces and so the titles appear as such. One improvement there would be to automatically add spaces to the titles, based on Capital letters in the name (and a few rules). I'll do some test with that idea and see how reliably it works.

@wepl 
Most of the collections I've seen, have the same name for both Icon and Slave. Do you have examples of how it looks like in your case, so I can prepare some tests here and implement such a scanner?

**Comment by MrZammler** [comment]
I think we need to define what a WHDLoad game is. Is it the slave file? Is the directory it's in? Is it the .icon that launches it?

Since a "game" is an entry on the list, it should be well defined if we're going one day implementing slave updates, etc. It will also change what extra information is kept for each one (directory? icon?).

The first versions of iGame used the directory name for the game title. The "Alt" part was still used if a directory contained multiple slaves. (Eventually, when an entry in the list is double clicked, a slave will be executed. iGame does need to know which one).

To be honest, I didn't like it. The list needed a lot of work to be presentable. My OCD needed clean titles. From my point of view, a list with titles from the slaves vs a list with titles from the directories needs less work from the user (i.e. changing titles) to be nice and clean. But, ok, my setup might have been unique.

I also believed that the slave authors were responsible for providing a good title for the slave file, and since they already do it, it shouldn't matter where in the hard disk the game is.

Anyway, perhaps it needs a large rewrite. Maybe the list could contain the title and the exact slave on a second column, or keep more data, etc.

But it boils down to what a game is. Maybe an external online database could take care of that. Hash every slave, provide details for each game, and be done ?

**Comment by midwan** [comment]
@MrZammler 
I agree, we should define what a "game" is, for iGame.
For me, that would be the `.slave` file itself. That's what iGame needs to know in order to start a Game as well.

In an ideal world, the `.slave` files would contain the proper title and we'd be done with it. But unfortunately, that's not the case. And if you have large collections of games (like many do, these days), the list gets ugly really quick.

And then it's very difficult (or impossible, for some) for users to change the contents of the `.slave` file, to edit the Title. But changing a directory name is very easy, not to mention that many collections already have proper directory names today.

That was the idea behind this approach.

What @wepl mentioned is also a valid point. If you have multiple icons for the same `.slave` file, for different configurations I guess, you'd want those to show separately in the list.

What if we use an approach similar to MAME, with grouping?
If multiple Icons are found for the same `.slave`, they could be grouped under one Title in the list. The group can be expanded and you can see each entry (taking it's title from the Icon name), and launch it.

In the end, it's tricky to keep everyone satisfied of course. That's why I think it would be good to give users the option to choose their preferred method of scanning the titles. We can offer a reasonable default (maybe based on what most people requested, which currently seems to be Directory scanning), and have the other options there so they can change them.

E.g.
Titles by:
- Directories
- Slaves
- Icons

**Comment by walkero-gr** [comment]
What would happen if there is a game with the same folder name on multiple repositories, lets say one for AGA and one for OCS-ECS games?

I believe that the scanning of the games using the slave files is really slow, so if you change it to something faster, that is great. Then my proposal is to have an online source and a hashing method to retrieve the correct name of the game, wherever you have it stored, if the user wants to do that.

**Comment by walkero-gr** [comment]
> Even if you used a hash-based identification, you would still end up with duplicates if you had the same slave in multiple repos...

This is true, but I guess noone would have something like that. But it is possible have something like:
- ocs-ecs/z/zool/<game files>
- aga/z/zool/<game files>
Maybe it would be useful for the user to give a label to the repositories which will be appended to the game name on duplicates.

Just my two cents.

**Comment by midwan** [comment]
First update regarding this was in cef6e1e0ff2818320fa94db4f73a826b347cd008
There will be more, to add this as an option.

**Comment by MrZammler** [comment]
>  In an ideal world, the .slave files would contain the proper title and we'd be done with it. But unfortunately, that's not the case. And if you have large collections of games (like many do, these days), the list gets ugly really quick.

> And then it's very difficult (or impossible, for some) for users to change the contents of the .slave file, to edit the Title. But changing a directory name is very easy, not to mention that many collections already have proper directory names today.

Wait. Why would anyone want to change the directory name or the .slave file for this? Why isn't changing the title iGame displays through Game Properties enough ?

**Comment by MrZammler** [comment]
@walkero-gr 

Hey man! :-)

**Comment by midwan** [comment]
@MrZammler 
Because you probably don't want to edit a few thousand entries, by hand, one by one.
There are tools that can do that on all the directories (e.g. Directory Opus) with one click. ;-)

**Comment by midwan** [comment]
I've pushed ec8402c3e26e6b57ecf6650222d64829cc9a6d9c regarding this.
There's now a new tooltype, `SCANBYDIRS` (until we get a Settings window at least).
If this is enabled, then the scanning operation will take the Directory names as Game Titles.
If it's disabled, it will use the previous mode of operation (extracting the Titles from the Slave contents).

**Comment by MrZammler** [comment]
> @MrZammler
Because you probably don't want to edit a few thousand entries, by hand, one by one.
There are tools that can do that on all the directories (e.g. Directory Opus) with one click. ;-)

Anyway, it's pointless to further discuss this. I guess users can choose now where they want their titles to come from. I still believe that the title from slaves produces a better *initial* list, which will require less editing from a user to get right.

In an ideal world, iGame should work link an mp3 player/manager. Get the tags from the files, and perhaps extra info (genre, game version (AGA/OCS), publisher, etc). But that would be monumental work, since current slaves would need to be updated.

An online database with hashes could still work, but this database would need to be distributed with iGame since not all installations have network connectivity (and it be the slowest).

**Comment by midwan** [comment]
Agreed, this is already resolved and merged in now, so we can close the issue.
Let's take discussions about further improving this approach (e.g. with metadata downloaded from internet sources, database, hash checks etc) on separate issues, to avoid mixing things up.
