### ISSUE TITLE
Add/Remove single whdload entry

### ISSUE THREAD

**Issue by T0lk13n** [MrZammler/iGame#74]
An option I miss is a way to can add a single whdload game/demo without the need to rescan the whole repository.

But can remove (not hyde) an entry is even more important. I have a lot of different versions of the same game. Yes, I can remover the drawer and rescan the repository but with more than 7 files is a lot of bored.
Perhaps the remove option should delete the slave drawer.

What do you think?

**Comment by coldacid** [comment]
If a remove action is added, it should bring up a confirmation requester that asks whether or not to delete the game drawer as well, defaulting to false for the deletion option and cancel for the requester.

As for adding a single WHDLoad game, it should be the same as adding a non-WHDLoad game except you select the slave, based on the format of the gameslist file.

**Comment by coldacid** [comment]
@T0lk13n @MrZammler @walkero-gr Per discussion on PR #84, I think we're all aligned on renaming the menu item and the add game requester title (although what the new labels will be are to be decided). One other item of note exists for this use-case, however: We need to lowercase the ".slave" part of the filename so that the icon will be properly identified for launch purposes and so that we display the appropriate image in the sidebar if there's no iGame.iff in the drawer of the game.

**Comment by coldacid** [comment]
For the non-matching problem with slave filenames, I found a nice case-insensitive strstr on Stack Overflow if we don't mind including that in the code. Since GCC already has such a function `strcasestr()` I intend to give it that name instead of `stristr()` or the like. That leaves just renaming the menu item.

**Comment by coldacid** [comment]
@walkero-gr @T0lk13n @MrZammler any suggestions on what we should change the menu item and window title to say? Personally I think we should just drop "non-WHDLoad" so the menu item is "Add game..." and the window "Add a Game".

**Comment by T0lk13n** [comment]
I think that is ok. It's clear enough to me.
